services:
  backend1:
    build: ./backend
    environment:
      DATABASE_URL: sqlite:////data/microservice.db
    volumes:
      - shared_data:/data

  backend2:
    build: ./backend
    environment:
      DATABASE_URL: sqlite:////data/microservice.db
    volumes:
      - shared_data:/data

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - backend1
      - backend2

volumes:
  shared_data:
